php:
  build: .
  volumes:
    - .:/app
    - ./scripts/php.ini:/usr/local/etc/php/php.ini
  command: 'php-fpm'

app:
  image: nginx
  ports:
    - "8010:80"
  volumes:
    - .:/app
    - ./scripts/nginx.conf:/etc/nginx/nginx.conf
  links:
    - php